version: '3'

services:
  web:
    build: .
    command: python -u app.py
    ports:
      - 5000:80
    volumes:
      - .:/usr/src/app
#  links:
#    - db
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db
  db:
    image: mongo
  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5001:80 
    depends_on:
      - web 
